force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletín</label>
    <nameField>
        <displayFormat>Boletín-{0000}</displayFormat>
        <label>Boletín número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Calificacion__c/Calificacion__c.object-meta.xml
<CustomObject>
    <description>Calificaciones de los becarios</description>
    <label>Calificación</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Calificación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calificaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Calificacion__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletín</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Calificaciones</relationshipLabel>
    <relationshipName>Calificaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Calificacion__c/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Materia</label>
    <referenceTo>Materia__c</referenceTo>
    <relationshipLabel>Calificaciones</relationshipLabel>
    <relationshipName>Calificaciones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calificacion__c/fields/Primer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Primer_trimestre__c</fullName>
    <description>Nota de la materia en el primer trimestre.</description>
    <label>Primer trimestre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calificacion__c/fields/Segundo_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Segundo_trimestre__c</fullName>
    <description>Nota de la materia en el segundo trimestre.</description>
    <label>Segundo trimestre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calificacion__c/fields/Tercer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Tercer_trimestre__c</fullName>
    <description>Nota de la materia en el tercer trimestre.</description>
    <label>Tercer trimestre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inasistencia__c/Inasistencia__c.object-meta.xml
<CustomObject>
    <label>Inasistencia</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Inasistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inasistencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inasistencia__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletín</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Inasistencias</relationshipLabel>
    <relationshipName>Inasistencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inasistencia__c/fields/Primer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Primer_trimestre__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Primer trimestre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inasistencia__c/fields/Segundo_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Segundo_trimestre__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Segundo trimestre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inasistencia__c/fields/Tercer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Tercer_trimestre__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tercer trimestre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Materia__c/Materia__c.object-meta.xml
<CustomObject>
    <description>Materias o asignaturas cursadas por los becarios</description>
    <label>Materia</label>
    <nameField>
        <label>Materia Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BoletinDataService.cls
public with sharing class BoletinDataService {

    @AuraEnabled(Cacheable=true)
	public static List<Calificacion__c> getCalificaciones(String boletinId) {
        List<Calificacion__c> listaDeCalificaciones = [SELECT Id, Materia__r.Name, Primer_trimestre__c, Segundo_trimestre__c, Tercer_trimestre__c
                                                       FROM Calificacion__c
                                                       WHERE Boletin__c = :boletinId];
        return listaDeCalificaciones;
    }

    @AuraEnabled(Cacheable=true)
	public static List<Inasistencia__c> getInasistencias(String boletinId) {
        List<Inasistencia__c> listaDeInasistencias = [SELECT Id, Primer_trimestre__c, Segundo_trimestre__c, Tercer_trimestre__c
                                                      FROM Inasistencia__c
                                                      WHERE Boletin__c = :boletinId];
        return listaDeInasistencias;
    }

    @AuraEnabled
	public static String updateCalificacion(Object data) {
    	List<Calificacion__c> calificacionesForUpdate = (List<Calificacion__c>) JSON.deserialize(
        	JSON.serialize(data),
        	List<Calificacion__c>.class
    	);
		update calificacionesForUpdate;
    	return 'Boletín actualizado';
	}

    @AuraEnabled
	public static String updateInasistencia(Object data) {
    	List<Inasistencia__c> inasistenciaForUpdate = (List<Inasistencia__c>) JSON.deserialize(
        	JSON.serialize(data),
        	List<Inasistencia__c>.class
    	);
		update inasistenciaForUpdate;
    	return 'Inasistencia actualizada';
	}
}